set rtp+=/root/.local/lib/python3.7/site-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
set hlsearch
highlight Comment ctermfg=blue

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'powerline/powerline'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'scrooloose/nerdtree'

Plugin 'lithammer/vim-eighties'
Plugin 'rhysd/wallaby.vim'
Plugin 'theJian/Mogao'
Plugin 'scottymoon/vim-chalkboard'
Plugin 'rafalbromirski/vim-aurora'

Plugin 'caglartoklu/qbcolor.vim'
Plugin 'shapeoflambda/dark-purple.vim'
Plugin 'levelone/tequila-sunrise.vim'
Plugin 'ayu-theme/ayu-vim'
Plugin 'sainnhe/everforest'
"Plugin 'maslaral/eink.vim'
Plugin 'sainnhe/edge'
Plugin 'sainnhe/gruvbox-material'
Plugin 'arcticicestudio/nord-vim'
Plugin 'FrenzyExists/aquarium-vim'

Plugin 'ctrlpvim/ctrlp.vim'

Plugin 'hdima/python-syntax'
Plugin 'ekalinin/Dockerfile.vim'

" vim-go plugin
Plugin 'fatih/vim-go'

Plugin 'preservim/nerdcommenter'

" auto complete
"Plugin 'zxqfl/tabnine-vim'

call vundle#end()

filetype plugin indent on

" set color
syntax enable
set t_Co=256
set background=dark	
" sua trong file color lighter_black  4E4E4E -> 79CDCD
"colorscheme tequila-sunrise
colorscheme everforest
"hi Normal guibg=NONE ctermbg=NONE

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

"if has('termguicolors')
"    set termguicolors
"endif

let g:gruvbox_material_background = 'hard'
colorscheme gruvbox-material

" transparent bg
hi Normal guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE
hi EndOfBuffer guibg=NONE ctermbg=NONE
hi Comment term=NONE cterm=NONE ctermfg=NONE gui=italic guifg=NONE

map <C-n> :NERDTreeToggle<CR>
nmap ev :tabedit <CR>
"set expandtab ts=4 sw=4 ai	

" on off mode paste
set pastetoggle=<C-]>
set paste

let NERDTreeShowHidden=1

let python_highlight_all = 1
"filetype plugin indent on
" set laststatus=2 " Always display the statusline in all windows
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
let g:Powerline_symbols = "fancy"

set showtabline=2 " Always display the tabline, even if there is only one tab
"set tabline=%!tabber#TabLine()"

set encoding=utf-8
set guifont=Monaco:h11
set fileencodings=ucs-bom,utf8,prc
set guifontwide=NSimsun:h12

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
"let g:airline_theme='wombat'

" shortcuts to vimdiff, http://stackoverflow.com/questions/7309707/why-does-git-mergetool-opens-4-windows-in-vimdiff-id-expect-3
let mapleader=','
let g:mapleader=','

" change tab
nnoremap <C-Up> :tabprevious<CR>
nnoremap <C-Down> :tabnext<CR>

filetype plugin on

"""
"let g:NERDSpaceDelims = 1: This option tells NERDCommenter to add spaces between the comment delimiters and the commented text. For example, it would comment like # text instead of #text.
"The map commands bind certain key combinations to NERDCommenter functions. In this case:
"""

" Create default mappings
let g:NERDCreateDefaultMappings = 1
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1
" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'
" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1
" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1
" Enable NERDCommenterToggle to check all selected lines is commented or not 
let g:NERDToggleCheckAllLines = 1

""" Help
" comment: ,cc
" uncomment: ,c<space>
" invert comment: ,ci


"let g:go_fmt_autosave=0
set expandtab ts=4 sw=4 ai
highlight Comment ctermfg=blue

" on off mode paste
set paste
